version: '3.3'
services:
  dmshelper:
    image: sc-registry.fredhutch.org/dmshelper:latest
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dmshelper.rule=Host(`dmshelper.fredhutch.org`)"
        - "traefik.http.routers.dmshelper-secured.rule=Host(`dmshelper.fredhutch.org`)"
        - "traefik.http.routers.dmshelper.entrypoints=web,web-secured"
        - "traefik.http.services.dmshelper.loadbalancer.server.port=3838" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.dmshelper.tls=true"

networks:
  proxy:
    external: true
