#' Title
#'
#' @param input
#'
#' @return
#' @export
#'
#' @examples
oversight_lab <- function(input) {
  return(
    paste0(
      "<font color='OA799A'>Laboratory staff ",
      input$name_role,
      " will review data generated by this project on a ",
      input$review_frequency,
      " basis, identifying any datasets which should be shared and updating a lab-based repository of scientific datasets. That staff member will also maintain a database of experimental metadata associated with the underlying datasets.</font>"
    )
  )
}


oversight_collaborator <- function(input) {
  return(
    paste0(
      "<font color='OA799A'>Datasets generated by this project will be monitored and managed by ",
      input$name_role,
      ". They will review and update all experimental metadata on a ",
      input$review_frequency,
      " basis and maintain a database of experimental metadata associated with the underlying datasets.</font>"
    )
  )
}


oversight_self <- function(input) {
  return(
    paste0(
      "<font color='OA799A'>Oversight for, management of and compliance with this data management and sharing plan will be performed by ",
      input$name_role,
      " for this project. We will review our plan and identify any datasets that need to be shared, processed for sharing or updated ",
      input$review_frequency,
      ". Additionally, we will implement aspects of our plan ",
      input$review_addtnl,
      ".</font>"
    )
  )
}
