#' Title
#'
#' @param input
#'
#' @return
#' @export
#'
#' @examples
oversight_chunk <- function(input) {
  if (determine_cores(input)$genomics_flag) {
    #####
    oversight_chunk_temp <- c(
      yaml.load_file("template/genomics.yml")$oversight,
      paste0(
        "Execution of this Plan will be executed by <font color='OA799A'>",
        yaml.load_file("template/genomics.yml")$oversight_execution,
        ".</font>"
      )
    )
  } else {
    oversight_chunk_temp <- c("")
  }
  if (determine_cores(input)$proteomics_flag) {
    #####
    oversight_chunk_temp <-
      c(
        oversight_chunk_temp,
        if (yaml.load_file("template/proteomics.yml")$oversight %in% oversight_chunk_temp) {
          ""
        } else {
          yaml.load_file("template/proteomics.yml")$oversight
        },
        paste0(
          "Execution of this Plan will be executed by <font color='OA799A'>",
          if (yaml.load_file("template/proteomics.yml")$oversight_execution %in% oversight_chunk_temp) {
            ""
          } else {
            yaml.load_file("template/proteomics.yml")$oversight_execution
          },
          ".</font>"
        )
      )
  } else {
    oversight_chunk_temp <- c(oversight_chunk_temp, "")
  }

  return(oversight_chunk_temp)

}





#' Title
#'
#' @param input
#'
#' @return
#' @export
#'
#' @examples
oversight_lab <- function(input) {
  return(paste0(
    paste0("Laboratory staff <font color='OA799A'>",
           if (input$name_role == "") {
             " ___ "
           } else {
             input$name_role
           }),
    if (input$core_datatype %in% c("small_animal")) {
      "</font> will review data generated by this project <font color='OA799A'> during and at end of study and update lab-based repository of scientific datasets</font>. That staff member will also maintain a database of experimental metadata associated with the underlying datasets."
    } else {
      paste0(
        "</font> will review data generated by this project on a <font color='OA799A'>",
        if (input$review_frequency == "") {
          " ___ "
        } else {
          input$review_frequency
        },
        "</font> basis, identifying any datasets which should be shared and updating a lab-based repository of scientific datasets. That staff member will also maintain a database of experimental metadata associated with the underlying datasets."
      )
    }
  ))
}


oversight_collaborator <- function(input) {
  return(paste0(
    paste0(
      "Datasets generated by this project will be monitored and managed by <font color='OA799A'>",
      if (input$name_role == "") {
        " ___ "
      } else {
        input$name_role
      }
    ),
    if (input$core_datatype %in% c("large_animal")) {
      paste0(
        "</font>. They will review and update all experimental metadata <font color='OA799A'> at completion of studies and upon request by internal researchers</font>."
      )
    } else {
      paste0(
        "</font>. They will review and update all experimental metadata on a <font color='OA799A'>",
        if (input$review_frequency == "") {
          " ___ "
        } else {
          input$review_frequency
        },
        "</font> basis and maintain a database of experimental metadata associated with the underlying datasets."
      )
    }
  ))
}


oversight_self <- function(input) {
  return(
    paste0(
      "Oversight for, management of and compliance with this data management and sharing plan will be performed by <font color='OA799A'>",
      if (input$name_role == "") {
        " ___ "
      } else {
        input$name_role
      },
      "</font> for this project. We will review our plan and identify any datasets that need to be shared, processed for sharing or updated <font color='OA799A'>",
      if (input$review_frequency == "") {
        " ___ "
      } else {
        input$review_frequency
      },
      "</font>. Additionally, we will implement aspects of our plan <font color='OA799A'>",
      if (input$review_addtnl == "") {
        " ___ "
      } else {
        input$review_addtnl
      },
      ".</font>"
    )
  )
}
