#' Title
#'
#' @param input
#'
#' @return
#' @export
#'
tools_open <- function(input) {
  return(
    paste0(
      "All software developed as a part of this proposal will be developed in the open on <font color='OA799A'>",
      input$version_control,
      "</font> will be collected via <font color='OA799A'>",
      if (length(input$tool) == 0) {" ___ "} else {paste(input$tool, collapse = ", ")},
      "</font> with an MIT license. Software packages will be formally released via <font color='OA799A'>",
      if (length(input$platform) == 0) {" ___ "} else {paste(input$platform, collapse = ", ")},
      "</font>."
    )
  )
}


#' Title
#'
#' @param input
#'
#' @return
#' @export
#'
#' @examples
tools_semiopen <- function(input) {
  return(
    paste0(
      "All software developed as a part of this proposal, will be deposited after publication on <font color='OA799A'>",
      input$version_control,
      "</font> will be collected via <font color='OA799A'>",
      if (length(input$tool) == 0) {" ___ "} else {paste(input$tool, collapse = ", ")},
      "</font> with an MIT license. Software packages will be formally released via <font color='OA799A'>",
      if (length(input$platform) == 0) {" ___ "} else {paste(input$platform, collapse = ", ")},
      "</font>."
    )
  )
}


#' Title
#'
#' @return
#' @export
#'
#' @examples
tools_proprietary <- function() {
  return(
    paste0(
      "Software used on this proposal is proprietary and there is no mechanism for sharing these software publicly. We will provide step by step analysis instructions including complete descriptions of all software versions, parameter settings, intermediate analysis steps, and intermediate calculations. Where possible, we will include screenshots of analysis steps to support reproducibility of results."
    )
  )
}


#' Title
#'
#' @return
#' @export
#'
#' @examples
manipulation_custom <- function(input) {
  return(
    paste0(
      "The raw and processed data generated by this study can be accessed and manipulated using <font color='OA799A'>",
      if (input$data_manipulation_tool == "") {" ___ "} else {input$data_manipulation_tool},
      ".</font>"
    )
  )
}


#' Title
#'
#' @return
#' @export
#'
#' @examples
list_of_tools <- function(){
  return(
    c(
      "R scripts",
      "R packages",
      "Python libraries",
      "Jupyter Notebooks",
      "WDL Workflows",
      "Galaxy Workflows",
      "NextFlow Workflows"
    )
  )
}


#' Title
#'
#' @return
#' @export
#'
#' @examples
list_of_platforms <- function(){
  return(
    c(
      "Bioconductor",
      "CRAN",
      "conda",
      "PyPi",
      "Galaxy Workbench",
      "AnVIL"
    )
  )
}
